[2025-09-01T14:19:00.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-01T14:19:00.737+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data scheduled__2025-08-31T00:00:00+00:00 [queued]>
[2025-09-01T14:19:00.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data scheduled__2025-08-31T00:00:00+00:00 [queued]>
[2025-09-01T14:19:00.867+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-01T14:19:00.973+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-08-31 00:00:00+00:00
[2025-09-01T14:19:01.018+0000] {standard_task_runner.py:63} INFO - Started process 168 to run task
[2025-09-01T14:19:01.052+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'load_data', 'scheduled__2025-08-31T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpsy3tf_2j']
[2025-09-01T14:19:01.063+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask load_data
[2025-09-01T14:19:01.187+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T14:19:01.693+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.load_data scheduled__2025-08-31T00:00:00+00:00 [running]> on host 6aba05baf296
[2025-09-01T14:19:02.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-31T00:00:00+00:00'
[2025-09-01T14:19:02.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-01T14:25:55.390+0000] {logging_mixin.py:188} INFO - ✅ Berhasil load data dari: /opt/***/datasets/online_retail.xlsx
[2025-09-01T14:25:55.392+0000] {logging_mixin.py:188} INFO - ==================================================
[2025-09-01T14:25:55.396+0000] {logging_mixin.py:188} INFO - DEBUG: DATA STRUCTURE
[2025-09-01T14:25:55.400+0000] {logging_mixin.py:188} INFO - ==================================================
[2025-09-01T14:25:55.402+0000] {logging_mixin.py:188} INFO - Columns in DataFrame: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
[2025-09-01T14:25:55.403+0000] {logging_mixin.py:188} INFO - Number of rows: 541909
[2025-09-01T14:25:55.404+0000] {logging_mixin.py:188} INFO - 
First 5 rows:
[2025-09-01T14:25:55.712+0000] {logging_mixin.py:188} INFO -   InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]
[2025-09-01T14:25:55.713+0000] {logging_mixin.py:188} INFO - 
Data types:
[2025-09-01T14:25:55.715+0000] {logging_mixin.py:188} INFO - InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object
[2025-09-01T14:25:55.715+0000] {logging_mixin.py:188} INFO - ==================================================
[2025-09-01T14:26:01.934+0000] {logging_mixin.py:188} INFO - ✅ Data berhasil disimpan ke: /tmp/orders.csv
[2025-09-01T14:30:11.177+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-09-01T14:30:11.230+0000] {process_utils.py:132} INFO - Sending 15 to group 168. PIDs of all processes in the group: [168]
[2025-09-01T14:30:11.247+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 168
[2025-09-01T14:30:11.283+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-01T14:30:11.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-01T14:30:11.478+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ecommerce_pipeline_dag.py", line 13, in run_load_data
    main()
  File "/opt/airflow/etl/load_data.py", line 149, in main
    load_to_postgres(df, "orders")
  File "/opt/airflow/etl/load_data.py", line 68, in load_to_postgres
    cur.execute(
  File "/usr/local/lib/python3.10/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-01T14:30:11.541+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_pipeline, task_id=load_data, run_id=scheduled__2025-08-31T00:00:00+00:00, execution_date=20250831T000000, start_date=20250901T141900, end_date=20250901T143011
[2025-09-01T14:30:12.771+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=168, status='terminated', exitcode=2, started='14:19:00') (168) terminated with exit code 2
[2025-09-01T14:30:12.773+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-09-01T14:30:12.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
