[2025-08-28T08:12:50.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T08:12:50.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T08:12:50.587+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.load_data manual__2025-08-28T07:21:41.282152+00:00 [queued]>
[2025-08-28T08:12:50.589+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 5
[2025-08-28T08:12:50.615+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-08-28 07:21:41.282152+00:00
[2025-08-28T08:12:50.624+0000] {standard_task_runner.py:63} INFO - Started process 644 to run task
[2025-08-28T08:12:50.628+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'load_data', 'manual__2025-08-28T07:21:41.282152+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpo8_kh_59']
[2025-08-28T08:12:50.631+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask load_data
[2025-08-28T08:12:50.653+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T08:12:50.701+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.load_data manual__2025-08-28T07:21:41.282152+00:00 [running]> on host 6aba05baf296
[2025-08-28T08:12:50.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T07:21:41.282152+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T07:21:41.282152+00:00'
[2025-08-28T08:12:50.818+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T08:12:51.646+0000] {logging_mixin.py:188} INFO - ❌ Error loading Excel file: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-08-28T08:12:51.647+0000] {logging_mixin.py:188} INFO - ❌ ETL process failed: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-08-28T08:12:51.648+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T08:12:51.649+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ecommerce_pipeline_dag.py", line 13, in run_load_data
    main()
  File "/opt/airflow/etl/load_data.py", line 129, in main
    df = load_excel_to_dataframe(excel_path)
  File "/opt/airflow/etl/load_data.py", line 114, in load_excel_to_dataframe
    df = pd.read_excel(file_path)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-08-28T08:12:51.673+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_pipeline, task_id=load_data, run_id=manual__2025-08-28T07:21:41.282152+00:00, execution_date=20250828T072141, start_date=20250828T081250, end_date=20250828T081251
[2025-08-28T08:12:51.694+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task load_data (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 644)
[2025-08-28T08:12:51.725+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T08:12:51.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T08:12:51.768+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
