[2025-09-04T03:20:45.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-04T03:20:45.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T03:20:45.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T03:20:45.702+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-04T03:20:45.846+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): daily_sales> on 2025-09-03 00:00:00+00:00
[2025-09-04T03:20:45.863+0000] {standard_task_runner.py:63} INFO - Started process 2610 to run task
[2025-09-04T03:20:45.885+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'daily_sales', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpe047twko']
[2025-09-04T03:20:45.889+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask daily_sales
[2025-09-04T03:20:45.997+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-04T03:20:46.145+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.daily_sales scheduled__2025-09-03T00:00:00+00:00 [running]> on host 6aba05baf296
[2025-09-04T03:20:46.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arel' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='daily_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-09-04T03:20:46.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-04T03:20:46.913+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-04T03:20:46.921+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=*** psql -h postgres -U *** -d *** -f /opt/***/sql/daily_sales.sql']
[2025-09-04T03:20:47.031+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T03:20:47.267+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:1: NOTICE:  table "daily_sales" does not exist, skipping
[2025-09-04T03:20:47.270+0000] {subprocess.py:93} INFO - DROP TABLE
[2025-09-04T03:20:47.272+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:12: ERROR:  relation "transactions" does not exist
[2025-09-04T03:20:47.273+0000] {subprocess.py:93} INFO - LINE 7: FROM transactions
[2025-09-04T03:20:47.283+0000] {subprocess.py:93} INFO -              ^
[2025-09-04T03:20:47.286+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:14: ERROR:  relation "daily_sales" does not exist
[2025-09-04T03:20:47.288+0000] {subprocess.py:93} INFO - psql:/opt/***/sql/daily_sales.sql:16: ERROR:  relation "daily_sales" does not exist
[2025-09-04T03:20:47.291+0000] {subprocess.py:93} INFO - LINE 1: SELECT * FROM daily_sales ORDER BY sales_date LIMIT 10;
[2025-09-04T03:20:47.292+0000] {subprocess.py:93} INFO -                       ^
[2025-09-04T03:20:47.306+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-04T03:20:47.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-04T03:20:47.430+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecommerce_pipeline, task_id=daily_sales, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20250904T032045, end_date=20250904T032047
[2025-09-04T03:20:47.559+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-04T03:20:47.581+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
